/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Harsh
 */
public class Admin_Login extends javax.swing.JFrame {
        
    /**
     * Creates new form Admin_Login
     */
     String password;
     
     static String username;
    public Admin_Login() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void User_Verification(String username , String password)
    {
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
           
            String sql ="select * from  admindb where username = ? and Password = ?";
            
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,username);
            pst.setString(2,password);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
             new Admin_DashBoardMain().setVisible(true);
            this.dispose();
            }
            
            else
            {
                JOptionPane.showMessageDialog(this , "Wrong Username and Password");
            }
        }
    
        catch(Exception e)
        {
            
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Heading = new javax.swing.JPanel();
        University_Logo = new javax.swing.JLabel();
        University_Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Cross = new javax.swing.JButton();
        Btn_Minimize = new javax.swing.JButton();
        Pnl_Right = new javax.swing.JPanel();
        Lbl_SignIn = new javax.swing.JLabel();
        Lbl_Username = new javax.swing.JLabel();
        Lbl_Password = new javax.swing.JLabel();
        tf_AdminUsername = new javax.swing.JTextField();
        tf_AdminPassword = new javax.swing.JPasswordField();
        Btn_AdminLogin = new javax.swing.JButton();
        Separotor_Password = new javax.swing.JSeparator();
        Lbl_UserLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lbl_error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Heading.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Heading.setPreferredSize(new java.awt.Dimension(1600, 65));
        Panel_Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        University_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        University_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/MAINPAINT-removebg-preview.png"))); // NOI18N
        Panel_Heading.add(University_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        University_Name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        University_Name.setForeground(new java.awt.Color(220, 41, 62));
        University_Name.setText("University");
        Panel_Heading.add(University_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(152, 32, 82));
        jLabel1.setText("University Portal");
        Panel_Heading.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 50));

        Btn_Cross.setBackground(new java.awt.Color(255, 0, 0));
        Btn_Cross.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Btn_Cross.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cross.setText("X");
        Btn_Cross.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Btn_Cross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrossActionPerformed(evt);
            }
        });
        Panel_Heading.add(Btn_Cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(1529, -5, 70, 70));

        Btn_Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Btn_Minimize.setText("--");
        Btn_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Btn_Minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MinimizeActionPerformed(evt);
            }
        });
        Panel_Heading.add(Btn_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 70, 70));

        getContentPane().add(Panel_Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Pnl_Right.setBackground(new java.awt.Color(153, 153, 153,30));
        Pnl_Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_SignIn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 52)); // NOI18N
        Lbl_SignIn.setForeground(new java.awt.Color(0, 0, 153));
        Lbl_SignIn.setText("Sign In");
        Pnl_Right.add(Lbl_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 200, 100));

        Lbl_Username.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        Lbl_Username.setText(" UserName :");
        Pnl_Right.add(Lbl_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, 60));

        Lbl_Password.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        Lbl_Password.setText("Password :");
        Pnl_Right.add(Lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        tf_AdminUsername.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_AdminUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_AdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AdminUsernameActionPerformed(evt);
            }
        });
        Pnl_Right.add(tf_AdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 230, 50));

        tf_AdminPassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_AdminPassword.setBorder(null);
        Pnl_Right.add(tf_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 230, 50));

        Btn_AdminLogin.setBackground(new java.awt.Color(6, 135, 246));
        Btn_AdminLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Btn_AdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_AdminLogin.setText("Login");
        Btn_AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AdminLoginActionPerformed(evt);
            }
        });
        Pnl_Right.add(Btn_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 190, 60));

        Separotor_Password.setBackground(new java.awt.Color(0, 0, 0));
        Separotor_Password.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Right.add(Separotor_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 230, -1));

        Lbl_UserLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/Username_Logo.png"))); // NOI18N
        Pnl_Right.add(Lbl_UserLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/Password.logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        Pnl_Right.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 80, 80));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Pnl_Right.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, 690));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Pnl_Right.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 630, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Pnl_Right.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 690));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_Right.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 630, -1));

        jSeparator6.setBackground(new java.awt.Color(51, 255, 0));
        Pnl_Right.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, -1));

        lbl_error.setForeground(new java.awt.Color(255, 0, 51));
        lbl_error.setText(" ");
        Pnl_Right.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 390, 40));

        getContentPane().add(Pnl_Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 830, 840));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/booksLoginPage.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1600, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MinimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_MinimizeActionPerformed

    private void tf_AdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AdminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AdminUsernameActionPerformed

    private void Btn_CrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrossActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Btn_CrossActionPerformed

    private void Btn_AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AdminLoginActionPerformed
        // TODO add your handling code here:
        
         username = tf_AdminUsername.getText();
         password = tf_AdminPassword.getText();
         
         if(username.trim().equals("") || password.trim().equals(""))
         {
             lbl_error.setText("Please Enter Username and Password!");
         }
         else
         {
             User_Verification(username , password);
             
         }
         
    }//GEN-LAST:event_Btn_AdminLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AdminLogin;
    private javax.swing.JButton Btn_Cross;
    private javax.swing.JButton Btn_Minimize;
    private javax.swing.JLabel Lbl_Password;
    private javax.swing.JLabel Lbl_SignIn;
    private javax.swing.JLabel Lbl_UserLogo;
    private javax.swing.JLabel Lbl_Username;
    private javax.swing.JPanel Panel_Heading;
    private javax.swing.JPanel Pnl_Right;
    private javax.swing.JSeparator Separotor_Password;
    private javax.swing.JLabel University_Logo;
    private javax.swing.JLabel University_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JPasswordField tf_AdminPassword;
    private javax.swing.JTextField tf_AdminUsername;
    // End of variables declaration//GEN-END:variables
}
